### PR TITLE
im-relay: fix text inputs created while a non-wlr node is focused

### LINKED ISSUE #2174: Crash when using Super+RMB to resize Discord client
**Describe the bug**
When I use the default configuration bind of Super+RMB to resize Discord, as of 80569f47, it crashes in the same place consistently.

**To Reproduce**
1. Use mostly default configuration with Xwayland-hidpi-xprop and wlroots-hidpi-xprop patches applied, and scale factor of 2.
2. Start Discord with Wayfire session
3. Super+RMB increase the size of the window
4. Wayfire crashes in the same place every time

**Expected behavior**
Window should resize, without crashing due to this dereference.

**Screenshots or stacktrace**
Stack trace:
```
Core was generated by `wayfire'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005e54c22016f8 in operator() (__closure=<optimized out>, data=0x5e54c3fd1dc0)
    at ../src/core/seat/input-method-relay.cpp:27
27                  auto surface = wf::node_to_view(focus)->get_keyboard_focus_surface();
[Current thread is 1 (Thread 0x71737ac2a9c0 (LWP 362016))]
(gdb) bt
#0  0x00005e54c22016f8 in operator() (__closure=<optimized out>, data=0x5e54c3fd1dc0)
    at ../src/core/seat/input-method-relay.cpp:27
#1  std::__invoke_impl<void, wf::input_method_relay::input_method_relay()::<lambda(void*)>&, void*>
    (__f=<optimized out>) at /usr/include/c++/13.2.1/bits/invoke.h:61
#2  std::__invoke_r<void, wf::input_method_relay::input_method_relay()::<lambda(void*)>&, void*>
    (__fn=<optimized out>) at /usr/include/c++/13.2.1/bits/invoke.h:111
#3  std::_Function_handler<void(void*), wf::input_method_relay::input_method_relay()::<lambda(void*)> >::_M_invoke(const std::_Any_data &, void *&&) (__functor=<optimized out>, __args#0=<optimized out>)
    at /usr/include/c++/13.2.1/bits/std_function.h:290
#4  0x00005e54c21bf71e in std::function<void (void*)>::operator()(void*) const
    (__args#0=<optimized out>, this=<optimized out>) at /usr/include/c++/13.2.1/bits/std_function.h:591
#5  wf::wl_listener_wrapper::emit (data=<optimized out>, this=<optimized out>)
    at ../src/wl-listener-wrapper.tpp:57
#6  wf::handle_wrapped_listener (listener=<optimized out>, data=<optimized out>)
    at ../src/wl-listener-wrapper.tpp:10
#7  0x000071737ba6901e in wl_signal_emit_mutable (signal=<optimized out>, data=0x5e54c3fd1dc0)
    at ../wayland-1.22.0/src/wayland-server.c:2241
#8  0x000071737af31596 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#9  0x000071737af2e00e in ffi_call_int
    (cif=cif@entry=0x7ffcae704d50, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#10 0x000071737af30bd3 in ffi_call
    (cif=cif@entry=0x7ffcae704d50, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7ffcae704e20) at ../src/x86/ffi64.c:710
#11 0x000071737ba67ada in wl_closure_invoke (closure=closure@entry=0x5e54c3a56a90, target=<optimized out>,
    target@entry=0x5e54c409cdb0, opcode=opcode@entry=1, data=<optimized out>,
    data@entry=0x5e54c3db3a70, flags=2) at ../wayland-1.22.0/src/connection.c:1025
#12 0x000071737ba6c180 in wl_client_connection_data
    (fd=<optimized out>, mask=<optimized out>, data=<optimized out>)
    at ../wayland-1.22.0/src/wayland-server.c:438
#13 0x000071737ba6aae2 in wl_event_loop_dispatch (loop=0x5e54c29b4cc0, timeout=timeout@entry=-1)
    at ../wayland-1.22.0/src/event-loop.c:1027
#14 0x000071737ba6b2d7 in wl_display_run (display=0x5e54c29b4bd0) at ../wayland-1.22.0/src/wayland-server.c:1493
#15 0x00005e54c21bdd06 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:418
```

**Wayfire version**
wayfire-hidpi-xprop-git 0.8.0.r118.g80569f47-1

### LINKED ISSUE #2175: xdg_popup crash
~ ❯❯❯ wayfire --version
0.9.0-80569f47 (Mar  2 2024) branch makepkg

Don't know to reproduce, but randomly the xdg popup will crash the compositor

EE 04-03-24 22:07:37.522 - [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x575b2e1bf140
EE 04-03-24 22:07:37.537 - [src/main.cpp:131] Fatal error: Segmentation fault
EE 04-03-24 22:07:37.672 - #1  signal_handler(int) ../src/main.cpp:133
EE 04-03-24 22:07:37.682 - #2  __sigaction ??:?
EE 04-03-24 22:07:37.818 - #3  std::_Function_handler<void (void*), wf::input_method_relay::input_method_relay()::{lambda(void*)#1}>::_M_invoke(std::_Any_data const&, void*&&) :?
EE 04-03-24 22:07:37.953 - #4  wf::handle_wrapped_listener(wl_listener*, void*) ../src/wl-listener-wrapper.tpp:11
EE 04-03-24 22:07:37.962 - #5  wl_signal_emit_mutable ??:?
EE 04-03-24 22:07:37.971 - #6  ffi_prep_go_closure ??:?
EE 04-03-24 22:07:37.981 - #7  ?? ??:0
EE 04-03-24 22:07:37.989 - #8  ffi_call ??:?
EE 04-03-24 22:07:37.998 - #9  ?? ??:0
EE 04-03-24 22:07:38.007 - #10 wl_array_add ??:?
EE 04-03-24 22:07:38.016 - #11 wl_event_loop_dispatch ??:?
EE 04-03-24 22:07:38.025 - #12 wl_display_run ??:?
EE 04-03-24 22:07:38.158 - #13 main ../src/main.cpp:421
EE 04-03-24 22:07:38.168 - #14 __libc_init_first ??:?
EE 04-03-24 22:07:38.177 - #15 __libc_start_main ??:?
EE 04-03-24 22:07:38.312 - #16 _start ??:?
(EE) failed to read Wayland events: Broken pipe

and there is also this one where I am not sure if both is related

EE 04-03-24 22:08:35.144 - [src/main.cpp:131] Fatal error: Segmentation fault
EE 04-03-24 22:08:35.277 - #1  signal_handler(int) ../src/main.cpp:133
EE 04-03-24 22:08:35.287 - #2  __sigaction ??:?
EE 04-03-24 22:08:35.420 - #3  std::_Function_handler<void (void*), wf::input_method_relay::input_method_relay()::{lambda(void*)#1}>::_M_invoke(std::_Any_data const&, void*&&) :?
EE 04-03-24 22:08:35.551 - #4  wf::handle_wrapped_listener(wl_listener*, void*) ../src/wl-listener-wrapper.tpp:11
EE 04-03-24 22:08:35.560 - #5  wl_signal_emit_mutable ??:?
EE 04-03-24 22:08:35.569 - #6  ffi_prep_go_closure ??:?
EE 04-03-24 22:08:35.578 - #7  ?? ??:0
EE 04-03-24 22:08:35.586 - #8  ffi_call ??:?
EE 04-03-24 22:08:35.595 - #9  ?? ??:0
EE 04-03-24 22:08:35.604 - #10 wl_array_add ??:?
EE 04-03-24 22:08:35.612 - #11 wl_event_loop_dispatch ??:?
EE 04-03-24 22:08:35.621 - #12 wl_display_run ??:?
EE 04-03-24 22:08:35.753 - #13 main ../src/main.cpp:421
EE 04-03-24 22:08:35.763 - #14 __libc_init_first ??:?
EE 04-03-24 22:08:35.772 - #15 __libc_start_main ??:?
EE 04-03-24 22:08:35.906 - #16 _start ??:?
(EE) failed to read Wayland events: Broken pipe

### PR DESCRIPTION
**Pull request by ammen99**
Fixes #2175
Fixes #2174

### CODE REVIEW

File: src/core/seat/input-method-relay.cpp [hunk 1]
```diff
@@ -24,12 +24,14 @@ wf::input_method_relay::input_method_relay()
...
         if (auto focus = seat->priv->keyboard_focus)
         {
-            auto surface = wf::node_to_view(focus)->get_keyboard_focus_surface();
-
-            if (surface && (wl_resource_get_client(wlr_text_input->resource) ==
-                            wl_resource_get_client(surface->resource)))
+            if (auto view = wf::node_to_view(focus))
             {
-                wlr_text_input_v3_send_enter(wlr_text_input, surface);
+                auto surface = wf::node_to_view(focus)->get_keyboard_focus_surface();
```
Comment (kode54) [inline src/core/seat/input-method-relay.cpp:29]: Why does this resolve wf::node_to_view(focus) twice? Can't this second invocation be:

```
auto surface = view->get_keyboard_focus_surface();
```

Comment (ammen99) [reply src/core/seat/input-method-relay.cpp:29]: yes it could, I missed that
