### PR TITLE
core: Add option to focus a view on mouse click even if modifiers are pressed

### LINKED ISSUE #657: make middle-click also focus the view below the mouse
wayfire supports the middle click (what's its name) secondary paste,
but it is broken in the even of pasting into unfocused window.

the normal kde, gnome, x, etc behavior is when you 
1) mark something in window X and window X is focused
2) middle click into window Y text 
3) window Y becomes focused  and text is pasted

Current behavior:
Nothing happens

EDIT: sway behavior is mouse follows focus so I guess not relevant

### PR DESCRIPTION
**Pull request by dkondor**
This addresses the second part of my issue #891 by allowing a view to be focused by a modifier + mouse click. In my opinion, this behavior is more consistent. Also, this ensures that the clicked view receives the modifier state (since it is always focused).

I've implemented this as an option, with the old behavior being the default.

Depends on https://github.com/WayfireWM/wf-config/pull/36

Currently, click-to-focus only works for mouse clicks without keyboard modifiers. If a modifier is held down, the necessary button binding in the focus handler does not match, so the focus does not change. The view under the mouse receives the mouse click, but not the state of the keyboard modifiers (since it never receives keyboard focus).

This commit adds an option to essentially ignore pressed modifiers for the purpose of focusing the clicked view, so this will work consistently regardless of the state of keyboard modifiers.

Fixes #657

### CODE REVIEW

**Comment by ammen99** [comment]
I would much rather implement it in a different way. Instead of relying on button bindings, just listen for direct button press signals. This would also solve #657

**Comment by dkondor** [comment]
> I would much rather implement it in a different way. Instead of relying on button bindings, just listen for direct button press signals. This would also solve #657

I was thinking of this (but this needs more changes); I'll look into this.

**Comment by dkondor** [comment]
This is actually simpler than I expected. What I actually don't like with this change is that it splits the focusing implementation between core/wm.cpp and core/seat/pointer.cpp -- I wonder if it would be better to keep the main functionality in wm.cpp and call it from pointer.cpp

**Comment by ammen99** [comment]
> This is actually simpler than I expected. What I actually don't like with this change is that it splits the focusing implementation between core/wm.cpp and core/seat/pointer.cpp -- I wonder if it would be better to keep the main functionality in wm.cpp and call it from pointer.cpp

You don't have to do that - there are events that the focus plugin can listen to.

https://github.com/WayfireWM/wayfire/blob/87d9e5bdc7e1df157e238e607d390a3cbbd81328/src/api/wayfire/signal-definitions.hpp#L82

**Comment by dkondor** [comment]
> You don't have to do that - there are events that the focus plugin can listen to.
> 
> https://github.com/WayfireWM/wayfire/blob/87d9e5bdc7e1df157e238e607d390a3cbbd81328/src/api/wayfire/signal-definitions.hpp#L82

I see; I've created an alternative version with this.

My problem in this case is that there is no way to not change focus if the click was handled by a plugin; this can mess up things if a plugin wants to manipulate focus. E.g. this is a problem for my [mouse gesture plugin](https://github.com/dkondor/wstroke). To mitigate this, I've added options to enable / disable focus behavior separately with the middle and right mouse buttons. This solves the problem in my case (since I use a right click to start gestures -- I could also add an option there to change focus), but it might come up with other plugins that try to change focus.

**Comment by ammen99** [comment]
> My problem in this case is that there is no way to not change focus if the click was handled by a plugin; this can mess up things if a plugin wants to manipulate focus.

How is this different from before?

File: src/core/wm.cpp [hunk 1]
```diff
@@ -109,14 +111,26 @@ void wayfire_focus::init()
...
+            return;
+        }
+
+        if ((!focus_modifiers && wf::get_core().get_keyboard_modifiers()) ||
+            ((ev->event->button == BTN_MIDDLE) && !focus_btn_middle) ||
+            ((ev->event->button == BTN_RIGHT) && !focus_btn_right))
+        {
+            return;
+        }
+
```
Comment (ammen99) [inline src/core/wm.cpp:130]: There are other buttons, for example BTN_EXTRA, BTN_FORWARD, etc.
I don't think we should change focus with such buttons.

Also, what do you think of creating an activator binding, which is used to match the button? I.e the user would list all the buttons they want to cause focus change, and then this focus plugin here will just match the button against the activator.

Comment (dkondor) [reply src/core/wm.cpp:130]: Yes, that's a good idea; it actually makes the result more flexible. I've made this into an option. There are two small UI issues with this though:
 - any modifiers set are ignored (although I don't know why anyone would want to set them; but this could be easily added)
 - when changing this option in wcm, there is a scary warning message about setting a mouse button binding without any modifiers

**Comment by dkondor** [comment]
> > My problem in this case is that there is no way to not change focus if the click was handled by a plugin; this can mess up things if a plugin wants to manipulate focus.
> 
> How is this different from before?

Before, this issue could not come up, since only the left button was matched (it is unlikely that would be set as a plugin activator). With the default behavior, there shouldn't be any change though.

In my previous version, when the focus logic was in pointer.cpp, it could be skipped if a binding matched.

Anyway, it is working for my use case, and for all the official plugins (I don't think any of them tries to set the focus away from the clicked view) and if anyone else has this issue, that could be solved separately.

File: metadata/core.xml [hunk 2]
```diff
@@ -53,5 +53,15 @@
 			<_long>Sets the compositor render delay in milliseconds, which allows applications to render with low latency.</_long>
 			<default>-1</default>
 		</option>
+		<option name="focus_btn_mod" type="bool">
+			<_short>Focus on click if keyboard modifiers are pressed</_short>
+			<_long>Allow focusing the clicked view even if keyboard modifiers are pressed. Without this option, click-to-focus only works if no modifiers are pressed.</_long>
+			<default>false</default>
+		</option>
+		<option name="focus_btns" type="activator">
```
Comment (ammen99) [inline metadata/core.xml:61]: Can we rename this to `focus_buttons` ?

File: metadata/core.xml [hunk 3]
```diff
@@ -53,5 +53,15 @@
 			<_long>Sets the compositor render delay in milliseconds, which allows applications to render with low latency.</_long>
 			<default>-1</default>
 		</option>
+		<option name="focus_btn_mod" type="bool">
```
Comment (ammen99) [inline metadata/core.xml:56]: `focus_button_with_modifiers`

**Review by ammen99 — APPROVED** [review]
I'd prefer the full names of the bindings.

Otherwise, LGTM.

**Comment by dkondor** [comment]
> I'd prefer the full names of the bindings.
Sure, I've adjusted it

> Otherwise, LGTM.
Should I squash everything to one commit?

**Comment by ammen99** [comment]
Don't worry, I can squash the commits when merging.

**Comment by ammen99** [comment]
Thanks!
