### PR TITLE
cube: cubemap: Reset state on error

### LINKED ISSUE #530: [cube] cubemap crashes if no file / invalid file set
I have never used cubemap and TBH don't know what it is.
Although when no file is specified or a txt file is specified wayfire crashes.

https://stackoverflow.com/questions/12774207/fastest-way-to-check-if-a-file-exist-using-standard-c-c11-c
I wanted to implement the fastest method to check if the file exists but a txt file specified would crash wf as well and I don't know how to check if file == cubemap

### PR DESCRIPTION
**Pull request by soreau**
Call OpenGL::render_end() where needed and unbind cubemap texture.
Without this, rotate cube crashes when no cubemap image is set.
Fixes #530.

### CODE REVIEW

File: plugins/cube/cubemap.cpp [hunk 1]
```diff
@@ -51,7 +51,7 @@ void wf_cube_background_cubemap::reload_texture()
 
             GL_CALL(glDeleteTextures(1, &tex));
             tex = -1;
-            break;
+            goto render_end;
```
Comment (ammen99) [inline plugins/cube/cubemap.cpp:54]: I definitely don't see why this thing here is necessary?

File: plugins/cube/cubemap.cpp [hunk 2]
```diff
@@ -80,6 +81,7 @@ void wf_cube_background_cubemap::render_frame(const wf::framebuffer_t& fb,
     {
         GL_CALL(glClearColor(TEX_ERROR_FLAG_COLOR));
         GL_CALL(glClear(GL_COLOR_BUFFER_BIT));
+        OpenGL::render_end();
```
Comment (ammen99) [inline plugins/cube/cubemap.cpp:84]: +1

File: plugins/cube/cubemap.cpp (hunk 1 above)
Comment (soreau) [reply plugins/cube/cubemap.cpp]: Ah, I read it as `return` and not `break`. Indeed, it is not needed.
