### PR TITLE
Avoid crash when calling set_decoration with null frame

### LINKED ISSUE #311: Unloading decoration plugin crashes wayfire

### PR DESCRIPTION
**Pull request by soreau**
The decoration plugin calls set_decoration with a null frame
argument on unload which causes wayfire to crash. Handle this
case properly by resetting the frame and emitting decoration
changed signal. Fixes #311.

### CODE REVIEW

**Comment by ammen99** [comment]
Btw this should also fix #284

File: src/view/view.cpp [hunk 1]
```diff
@@ -482,6 +482,18 @@ bool wf::view_interface_t::should_be_decorated()
 
 void wf::view_interface_t::set_decoration(surface_interface_t *frame)
 {
+    if (!frame)
+    {
+        damage();
+        if (view_impl->decoration)
+            view_impl->decoration->unref();
+        view_impl->decoration = frame;
```
Comment (ammen99) [inline src/view/view.cpp]: i'd like to see it set to `nullptr` explicitly (frame is null anyway)

Comment (soreau) [reply src/view/view.cpp]: Yes, makes sense.

**Comment by ammen99** [comment]
Thanks!
