### PR TITLE
core: Set minimum workspaces to one

### LINKED ISSUE #1290: Accidentally setting workspace grid vheight or vwidth in [core] to zero crashes wayfire
Accidentally set vheight of workspace grid using the wcm configurator to zero. Wayfire immediately crashed kicking me back to the tty.

You can easily reproduce either by selecting 'core' in wcm and clicking Horizontal/Vertical virtual size minus sign until you reach zero OR editiing the ~/.config/wayfire.ini file and changing the value of vheight/vwidth to zero in the [core] stanza.

The configuration GUI should not allow a (meaningless) value of zero.

Wayfire version: 0.8.0-8 as provided by the debian/ubuntu PPA.

### PR DESCRIPTION
**Pull request by soreau**
Wayfire crashed if vwidth or vheight was set to <= 0. Set the minimum
vwidth and vheight to 1, so we always have at least one workspace.

Fixes #1290.

### CODE REVIEW

File: src/output/workspace-impl.cpp [hunk 1]
```diff
@@ -483,7 +483,8 @@ class output_viewport_manager_t
         }
 
         auto old_grid = grid;
-        grid = {vwidth_opt, vheight_opt};
+        grid = {vwidth_opt > 0 ? vwidth_opt : 1,
```
Comment (ammen99) [inline src/output/workspace-impl.cpp:486]: This clamping is not necessary, wf-config will sanitize the values once the option has a min/max in the .xml file

**Review by ammen99 — APPROVED** [review]
Thanks!
